services:
  - type: web
    name: ktpm-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm ci
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: MOMO_ACCESS_KEY
        sync: false
      - key: MOMO_PARTNER_CODE
        sync: false
      - key: MOMO_SECRET_KEY
        sync: false
